In [1]:
import os
os.chdir('/content/drive/MyDrive/python-performance')

In [2]:
!python image_processing.py

Image size: (182, 45)
Array shape, array type: (45, 182) uint8
Array size * item size:  8190
Array nbytes: 8190
sys.getsizeof: 8318
(182, 1) (-182, 1)
[[ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 ...
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]]
False True
1
None [[  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]
 ...
 [  0   0   0 ...  52  52  80]
 [  0   0   0 ...  52  52  80]
 [  0   0   0 ...  93 136 219]]
True
[[ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 ...
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]]


In [3]:
!python performance.py

1,2,0.4789359859999962,0.8821508099999988
10,20,0.43690232400000184,0.4817369909999911
100,200,0.1665186609999978,0.45079078400000583
1000,2000,0.15276385499998923,0.9587654209999954
10000,20000,0.16457017399999074,4.341908433
100000,200000,0.12356993699999919,47.443331852
200000,400000,0.09799827099999447,Traceback (most recent call last):
  File "/content/drive/MyDrive/python-performance/performance.py", line 15, in <module>
    copy_time = timeit.timeit(
                ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/timeit.py", line 237, in timeit
    return Timer(stmt, setup, timer, globals).timeit(number)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/timeit.py", line 180, in timeit
    timing = self.inner(it, self.timer)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<timeit-src>", line 6, in inner
KeyboardInterrupt
^C


In [6]:
!python array_and_broadcasting.py

Traceback (most recent call last):
  File "/content/drive/MyDrive/python-performance/array_and_broadcasting.py", line 16, in <module>
    x = np.array([[0, 20], [250, 500], [1, 2]],
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OverflowError: Python integer 500 out of bounds for uint8


In [4]:
!python image_views.py

original array (45, 182) (182, 1) uint8
invert rows (45, 182) (-182, 1) True
invert columns (45, 182) (182, -1) True
view_swap (182, 45) (45, 1) True
transpose (182, 45) (1, 182) True
rot_arr (182, 45) (-1, 182) True
slice_arr (30, 105) (182, 1) True


In [5]:
!python image_ops.py

255 uint8
255 uint8
254 uint8
510 uint16
255 uint16
255 uint8


In [8]:
!python double_wo_overflow.py

255 uint8
255 uint8 (45, 182)
/content/drive/MyDrive/python-performance/double_wo_overflow.py:37: RuntimeWarning: overflow encountered in scalar multiply
  v2 = 2 * v
255 uint8 (45, 182)


In [10]:
!python make_grayscale.py

(2048, 1367, 3) uint8
254 uint8 (2048, 1367)


In [11]:
import numpy as np
np.show_config()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc


In [12]:
!ls -l '/opt/_internal/cpython-3.11.8/lib/libcblas.so*'

ls: cannot access '/opt/_internal/cpython-3.11.8/lib/libcblas.so*': No such file or directory
